version: "3"
services:
    mutants:
      build: ./target/docker/com.meli/mutants/build
      image: mutants
      container_name: mutants
      deploy:
        resources:
          limits:
            memory: 400M
      ports:
        - "8080:8080"
        - "8181:8181"
      expose:
        - "8080"
        - "8181"
      depends_on:
        - mutants-db
      environment:
        - DB_HOSTNAME=mutants-db
        - DB_PORT=5432
        - DB_NAME=mutants
        - DB_USERNAME=mutants-app
        - DB_PWD=mutants-app
      links:
        - mutants-db:postgres.local

    mutants-db:
        build: ./src/db-schema
        image: com.meli/mutants-db
        container_name: mutants-db
        environment: 
          - POSTGRES_DB=mutants
        ports:
          - "5432"
        expose:
          - "5432"
